# Generated by Django 3.2.8 on 2021-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_venda_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='pagamento',
            field=models.CharField(choices=[('À Vista', 'À Vista'), ('180 Parcelas', '180 Parcelas')], max_length=255),
        ),
    ]
