# Generated by Django 3.2.8 on 2021-10-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_venda_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
