# Generated by Django 3.2.8 on 2021-10-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_venda_comissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='comissao',
        ),
    ]
